image_speed = 0
image_index = 0
image_xscale = 0.3335
image_yscale = 0.3335
effect_hover = 0
url = ""
press = 0
rot = 0
mensaje = ""
codigo = ""
	sess_start = "Session started"
	sess_errs = "Can't start session"
	agotad = "Connection timed out"
	retr_data = "Can't retrieve data"
internet = 0
time = 0
url_pass = 0
get = 0
