draw_sprite(spr_gb_cover1, 0, (camera_get_view_x(view_get_camera(0)) + 51), camera_get_view_y(view_get_camera(0)))
draw_sprite(spr_gb_cover2, 0, (camera_get_view_x(view_get_camera(0)) + 51), (camera_get_view_y(view_get_camera(0)) + 206))
draw_set_font(global.font_google)
draw_text_color((camera_get_view_x(view_get_camera(0)) + can_x), (camera_get_view_y(view_get_camera(0)) + 82), string_hash_to_newline((cantidad + "/99")), c_white, c_aqua, c_gray, c_blue, 1)
draw_sprite(spr_guardabot_tabs, 0, (camera_get_view_x(view_get_camera(0)) + 51), (camera_get_view_y(view_get_camera(0)) + 34))
draw_set_color(c_white)
draw_set_halign(fa_center)
draw_text((camera_get_view_x(view_get_camera(0)) + 192), (camera_get_view_y(view_get_camera(0)) + 35), string_hash_to_newline(livelli))
draw_set_halign(fa_left)