instance_activate_all()
if sprite_exists(back)
    sprite_delete(back)
with(obj_nm_panel_makers_close)
	instance_destroy()
with(obj_nm_card_2)
	instance_destroy()
with(obj_nm_panel_makers_top)
	instance_destroy()
with(obj_scrollbar4)
	instance_destroy()
with(obj_follown)
	instance_destroy()
obj_makers.active = 1