draw_set_font(global.font_hd)
draw_set_color(c_letter)
draw_set_halign(fa_center)
draw_text_transformed_color(x, (y + 32),adv[idioma],0.3334,0.3334,0,c_title, c_title, c_title, c_title,1)
draw_text_transformed(x, (y + 66),string_hash_to_newline(lng[idioma]),0.3334,0.3334,0)
draw_set_halign(fa_left)