image_speed = 0
image_index = 0
c_etiqueta = make_colour_rgb(89, 15, 16)
index = 0
idd = 0
selected = 0
disabled = 0
effect_hover = 0
anim = 0
text[0] = "Tradicional"
text[1] = "Puzles"
text[2] = "Contrarreloj"
text[3] = "Autoavance"
text[4] = "Automatismos"
text[5] = "Corto pero intenso"
text[6] = "Competitivo"
text[7] = "Tematico"
text[8] = "Música"
text[9] = "Artístico"
text[10] = "Habilidad"
text[11] = "Disparos"
text[12] = "Contra jefes"
text[13] = "En solitario"
text[14] = "Link"

