draw_sprite_ext(sprite_index, 0, x, y, image_xscale, image_yscale, 0, c_white, 1)
draw_sprite_ext(spr_nm_card_image, real(entorno), (x - 94), (y + 12), image_xscale, image_yscale, 0, c_white, 1)
draw_sprite_ext(spr_carteles_small, real(apariencia), (x + 98), y + 12, image_xscale, image_yscale, 0, c_white, 1)
draw_set_font(global.font_hd)
draw_set_color(c_color_name)
draw_text_transformed((x - 90), (y + 2), string_hash_to_newline(name), image_xscale, image_yscale, 0)
draw_sprite_ext(spr_nm_icons, 0, (x - 87), (y + 38), image_xscale, image_yscale, 0, c_white, 1)
draw_set_color(c_color)
draw_text_transformed((x - 73), (y + 40), string_hash_to_newline(likes), image_xscale, image_yscale, 0)
draw_sprite_ext(spr_nm_icons, 1, (x - (31 - (string_width(string_hash_to_newline(likes)/3) + 8))- 43), (y + 40), image_xscale, image_yscale, 0, c_white, 1)
draw_text_transformed((x - (30 - (string_width(string_hash_to_newline(likes)/3) + 21))- 43), (y + 40), string_hash_to_newline(intentos), image_xscale, image_yscale, 0)