image_speed = 0
image_index = 2
image_xscale = 0.3334
image_yscale = 0.3334
effect_hover = 0
url2 = ""
press = 0
rot = 0
mensaje = ""
codigo = ""
sess_start = "Complete registration"
sess_errs = "Sign up failed"
agotad = "Connection timed out"
retr_data = "Can't retrieve data"
internet = 0
time = 0
url_pass = 0
get = 0
