draw_self()
draw_set_font(global.font_hd)
draw_set_color(c_color)
draw_set_halign(fa_center)
draw_text_transformed(round(x + 41), (y + 4), string_hash_to_newline((text)),image_xscale,image_yscale,0)
draw_set_halign(fa_left)