with (obj_lun_reg)
    instance_destroy()
with (obj_lp2_reg)
    instance_destroy()
with (obj_lp_reg)
    instance_destroy()
with (obj_bl_reg)
    instance_destroy()
with (obj_iname_close)
    instance_destroy()
instance_activate_all()
if sprite_exists(back)
    sprite_delete(back)