draw_self()
draw_set_font(global.font_hd2)
draw_set_color(c_white)
draw_set_halign(fa_center)
draw_text_transformed((x + 57), (y + 9), string_hash_to_newline(text),0.3334,0.3334,0)
draw_set_halign(fa_left)